language: node_js
node_js:
  - 10

branches:
  except:
  - gh-pages

before_deploy:
  - pwd
  - rm -rf node_modules
  - npm install --production
  - git add -f ./node_modules/

deploy:
  provider: pages
  local_dir: ./
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
    branch: better-travis